# Generated by Django 4.2.11 on 2024-04-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='weight_goal',
            field=models.CharField(choices=[('G', 'Gain'), ('S', 'Stay'), ('L', 'Lose')], default='L', max_length=4),
        ),
    ]
