# Generated by Django 4.2.11 on 2024-03-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phys_lvl',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sub_goal',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='wlp',
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-Binary'), ('P', 'Prefer not to choose')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='physical_activity_level',
            field=models.CharField(choices=[('S', 'Sedentary'), ('LA', 'Low Active'), ('A', 'Active'), ('VA', 'Very Active')], default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='track_fat',
            field=models.BooleanField(default=False, help_text='Sub goal #1'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='track_salt',
            field=models.BooleanField(default=False, help_text='Sub goal #2'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='track_sugar',
            field=models.BooleanField(default=False, help_text='Sub goal #3'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='weight_goal',
            field=models.CharField(choices=[('G', 'Gain'), ('S', 'Stay'), ('L', 'Loss')], default='L', max_length=4),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='height',
            field=models.FloatField(help_text='in', verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='weight',
            field=models.FloatField(help_text='lbs', verbose_name='weight'),
        ),
    ]
