# Generated by Django 4.2.11 on 2024-10-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='daily_cal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='daily_carb',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='daily_cff',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='daily_pro',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='daily_sod',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='daily_sug',
            field=models.FloatField(default=0),
        ),
    ]
